const tudo = [
    {
        id:0,
        name: 'Centauro',
        local: 'Porto Alegre',
        state: 'RS',
        description: 'Loja de Departamento de artigos desportivos',
        category: 'Artigos desportivos',
        sports:['futebol', 'basquete', 'tênis'],
        contact: '(51)99999999',
        user: 'centauro',
        password: 'senhacentauro',
    },
    {
        id:1,
        name: 'Paquetá Esportes',
        local: 'Canoas',
        state:'RS',
        description: 'Tudo para esportes',
        category: 'Artigos desportivos',
        sports:['futebol', 'tênis', 'corrida'],
        contact: '(51)88888888',
        user: 'paqueta',
        password:'senhapaqueta',
    },
    {
        id:2,
        name: 'Genius Uniformes',
        local: 'Porto Alegre',
        state: 'RS',
        description: 'Uniformes para todos os esportes',
        category: 'Uniformes',
        sports:['futebol', 'basquete', 'tênis', 'natação'],
        contact: '(51)77777777',
        user:'genius',
        password:'senhagenius',
    },
    {
        id:3,
        name: 'AOC',
        local: 'Tramandaí',
        state: 'RS',
        description: 'Artigos para esportes náuticos',
        category:'Artigos Desportivos',
        sports:['vela','remo','surfe'],
        contact:'(51)666666666',
        user:'aoc',
        password:'senhaaoc',
    },
];